package net.redboltmedia.witchercraft.client.gui.shell;

/**
 * Data-driven geometry + content for the WitcherCraft GUI shell.
 *
 * All coordinates are GUI-LOCAL to the shell panel (top-left origin), in
 * Minecraft GUI pixels. The shell centres the panel via leftPos / topPos and
 * adds those itself, so values here are pure layout.
 *
 * Generated by tools/gui-layout-creator.html - paste this over the file
 * wholesale. Keep it a dumb data holder (no logic beyond the tiny lookups at
 * the bottom) so the tool can overwrite it freely.
 *
 * Two arrays drive everything:
 *   NAV[]      - the top navbar tabs (order = navbar order). Each links to a
 *                page by pageId; the matching {@link GuiPage} renders when the
 *                tab is active.
 *   SECTIONS[] - the "lower" content boxes, each tagged with the pageId it
 *                belongs to. {@link LayoutPage} renders the boxes for its page;
 *                custom pages (e.g. PerkPage) ignore these and draw themselves.
 */
public final class WitcherGuiLayout {
	private WitcherGuiLayout() {
	}

	// --- shell panel ----------------------------------------------------------
	public static final int PANEL_W = 360;
	public static final int PANEL_H = 252;

	// --- navbar band ----------------------------------------------------------
	public static final int NAV_Y = 4;
	public static final int NAV_H = 14;

	// --- content region (below the navbar; where the active page draws) -------
	public static final int CONTENT_X = 0;
	public static final int CONTENT_Y = 22;
	public static final int CONTENT_W = 360;
	public static final int CONTENT_H = 230;

	// ==========================================================================
	//  A navbar tab. pageId must match a GuiPage.id() to be interactive.
	// ==========================================================================
	public static final class Nav {
		public final String pageId;
		public final String labelKey; // lang key; may be "" to use the page's own label
		public final String icon; // texture path, or "" for none (label only)
		public final int x, y, w, h;

		public Nav(String pageId, String labelKey, String icon, int x, int y, int w, int h) {
			this.pageId = pageId;
			this.labelKey = labelKey;
			this.icon = icon;
			this.x = x;
			this.y = y;
			this.w = w;
			this.h = h;
		}
	}

	// ==========================================================================
	//  A content box on a page. type picks how it renders (placeholder art).
	// ==========================================================================
	public static final int TYPE_IMAGE = 0;
	public static final int TYPE_TEXT = 1;
	public static final int TYPE_SLOT = 2;

	public static final class Section {
		public final String pageId; // which page this box belongs to
		public final int type; // TYPE_IMAGE / TYPE_TEXT / TYPE_SLOT
		public final String text; // lang key or literal (TEXT), or caption
		public final String texture; // texture path (IMAGE), or "" placeholder
		public final String id; // stable id for later wiring
		public final int x, y, w, h;

		public Section(String pageId, int type, String text, String texture, String id, int x, int y, int w, int h) {
			this.pageId = pageId;
			this.type = type;
			this.text = text;
			this.texture = texture;
			this.id = id;
			this.x = x;
			this.y = y;
			this.w = w;
			this.h = h;
		}
	}

	// --- seeded navbar --------------------------------------------------------
	// 6 evenly spaced tabs. "skills" routes to the ported perk page (PerkPage).
	public static final Nav[] NAV = {
			new Nav("inventory", "gui.witchercraft.shell.nav.inventory", "", 8, 4, 54, 14),
			new Nav("skills", "gui.witchercraft.shell.nav.skills", "", 66, 4, 54, 14),
			new Nav("alchemy", "gui.witchercraft.shell.nav.alchemy", "", 124, 4, 54, 14),
			new Nav("bombs", "gui.witchercraft.shell.nav.bombs", "", 182, 4, 54, 14),
			new Nav("map", "gui.witchercraft.shell.nav.map", "", 240, 4, 54, 14),
			new Nav("glossary", "gui.witchercraft.shell.nav.glossary", "", 298, 4, 54, 14),
	};

	// --- seeded content boxes (placeholder panels per page) -------------------
	// "skills" has no boxes here - PerkPage draws itself. The rest are simple
	// placeholder layouts you rearrange in the tool.
	public static final Section[] SECTIONS = {
			// inventory: a big portrait area flanked by equip-slot columns + a bag
			new Section("inventory", TYPE_IMAGE, "PORTRAIT", "", "portrait", 150, 34, 90, 150),
			new Section("inventory", TYPE_SLOT, "WEAPON", "", "weapon", 40, 40, 24, 24),
			new Section("inventory", TYPE_SLOT, "ARMOR", "", "armor", 40, 72, 24, 24),
			new Section("inventory", TYPE_SLOT, "GLOVES", "", "gloves", 40, 104, 24, 24),
			new Section("inventory", TYPE_SLOT, "TROUSERS", "", "trousers", 296, 40, 24, 24),
			new Section("inventory", TYPE_SLOT, "BOOTS", "", "boots", 296, 72, 24, 24),
			new Section("inventory", TYPE_IMAGE, "BAG", "", "bag", 296, 120, 40, 40),
			new Section("inventory", TYPE_TEXT, "gui.witchercraft.shell.section.stats", "", "stats", 12, 196, 200, 28),
			// alchemy placeholder
			new Section("alchemy", TYPE_TEXT, "gui.witchercraft.shell.section.alchemy_todo", "", "todo", 12, 30, 300, 20),
			new Section("alchemy", TYPE_SLOT, "POTION", "", "potion1", 40, 60, 24, 24),
			new Section("alchemy", TYPE_SLOT, "POTION", "", "potion2", 72, 60, 24, 24),
			new Section("alchemy", TYPE_SLOT, "OIL", "", "oil1", 104, 60, 24, 24),
			// bombs placeholder
			new Section("bombs", TYPE_TEXT, "gui.witchercraft.shell.section.bombs_todo", "", "todo", 12, 30, 300, 20),
			new Section("bombs", TYPE_SLOT, "BOMB", "", "bomb1", 40, 60, 24, 24),
			new Section("bombs", TYPE_SLOT, "BOMB", "", "bomb2", 72, 60, 24, 24),
			// map placeholder
			new Section("map", TYPE_IMAGE, "MAP", "", "map", 20, 30, 320, 180),
			// glossary placeholder
			new Section("glossary", TYPE_TEXT, "gui.witchercraft.shell.section.glossary_todo", "", "todo", 12, 30, 300, 20),
	};

	// --- tiny lookups (kept trivial so the tool can regenerate the class) -----

	/** Sections belonging to a page, in declaration order. */
	public static java.util.List<Section> sectionsFor(String pageId) {
		java.util.List<Section> out = new java.util.ArrayList<>();
		for (Section s : SECTIONS)
			if (s.pageId.equals(pageId))
				out.add(s);
		return out;
	}

	/** Absolute-centred left edge for a panel of PANEL_W in a screen of width w. */
	public static int leftPos(int screenW) {
		return (screenW - PANEL_W) / 2;
	}

	public static int topPos(int screenH) {
		return (screenH - PANEL_H) / 2;
	}
}
