package net.redboltmedia.witchercraft.client.gui.shell;

/**
 * Data-driven geometry + content for the WitcherCraft GUI shell.
 *
 * The shell is FULLSCREEN: a background image fills the whole screen and the
 * navbar + active page are drawn on top of it. So most geometry here is
 * resolution-independent - the navbar is a centred group of fixed-width tabs,
 * and each page draws inside a centred content "safe area" (fixed size, so the
 * perk grid and other pages stay crisp and undistorted at any resolution).
 * Section coordinates are LOCAL to that content safe area (top-left origin).
 *
 * Generated by tools/gui-layout-creator.html - paste this over the file
 * wholesale. Keep it a dumb data holder (no logic beyond the small lookups at
 * the bottom) so the tool can overwrite it freely.
 */
public final class WitcherGuiLayout {
	private WitcherGuiLayout() {
	}

	// --- fullscreen background ------------------------------------------------
	// Blitted stretched to fill the screen. Swap this texture for the real art.
	public static final String BG = "witchercraft:textures/gui/shell/background.png";

	// --- navbar (centred group of fixed-width tabs, drawn over the background) -
	public static final int NAV_Y = 8; // top margin to the tab row
	public static final int NAV_H = 32; // tab height (icon + label)
	public static final int NAV_TAB_W = 92; // width of each tab
	public static final int NAV_GAP = 6; // gap between tabs
	public static final int NAV_ICON = 20; // icon square size, drawn at tab top

	// --- content safe area (centred; where the active page draws) -------------
	public static final int CONTENT_W = 360;
	public static final int CONTENT_H = 230;

	// ==========================================================================
	//  A navbar tab. pageId must match a GuiPage.id() to be interactive. Tab
	//  positions are computed (centred) by the shell, so there is no rect here.
	// ==========================================================================
	public static final class Nav {
		public final String pageId;
		public final String labelKey; // lang key; may be "" to use the page's own label
		public final String icon; // texture path, or "" for none (label only)

		public Nav(String pageId, String labelKey, String icon) {
			this.pageId = pageId;
			this.labelKey = labelKey;
			this.icon = icon;
		}
	}

	// ==========================================================================
	//  A content box on a page (coords LOCAL to the content safe area).
	// ==========================================================================
	public static final int TYPE_IMAGE = 0;
	public static final int TYPE_TEXT = 1;
	public static final int TYPE_SLOT = 2;

	public static final class Section {
		public final String pageId; // which page this box belongs to
		public final int type; // TYPE_IMAGE / TYPE_TEXT / TYPE_SLOT
		public final String text; // lang key or literal (TEXT), or caption
		public final String texture; // texture path (IMAGE), or "" placeholder
		public final String id; // stable id for later wiring
		public final int x, y, w, h;

		public Section(String pageId, int type, String text, String texture, String id, int x, int y, int w, int h) {
			this.pageId = pageId;
			this.type = type;
			this.text = text;
			this.texture = texture;
			this.id = id;
			this.x = x;
			this.y = y;
			this.w = w;
			this.h = h;
		}
	}

	// --- seeded navbar --------------------------------------------------------
	// "skills" routes to the ported perk page (PerkPage); the rest are LayoutPages.
	public static final Nav[] NAV = {
			new Nav("inventory", "gui.witchercraft.shell.nav.inventory", "witchercraft:textures/gui/nav/inventory.png"),
			new Nav("skills", "gui.witchercraft.shell.nav.skills", "witchercraft:textures/gui/nav/skills.png"),
			new Nav("alchemy", "gui.witchercraft.shell.nav.alchemy", "witchercraft:textures/gui/nav/alchemy.png"),
			new Nav("bombs", "gui.witchercraft.shell.nav.bombs", "witchercraft:textures/gui/nav/bombs.png"),
			new Nav("map", "gui.witchercraft.shell.nav.map", "witchercraft:textures/gui/nav/map.png"),
			new Nav("glossary", "gui.witchercraft.shell.nav.glossary", "witchercraft:textures/gui/nav/glossary.png"),
	};

	// --- seeded content boxes (placeholder panels per page) -------------------
	// "skills" has no boxes - PerkPage draws itself. Coords are content-local.
	public static final Section[] SECTIONS = {
			new Section("inventory", TYPE_IMAGE, "PORTRAIT", "", "portrait", 150, 34, 90, 150),
			new Section("inventory", TYPE_SLOT, "WEAPON", "", "weapon", 40, 40, 24, 24),
			new Section("inventory", TYPE_SLOT, "ARMOR", "", "armor", 40, 72, 24, 24),
			new Section("inventory", TYPE_SLOT, "GLOVES", "", "gloves", 40, 104, 24, 24),
			new Section("inventory", TYPE_SLOT, "TROUSERS", "", "trousers", 296, 40, 24, 24),
			new Section("inventory", TYPE_SLOT, "BOOTS", "", "boots", 296, 72, 24, 24),
			new Section("inventory", TYPE_IMAGE, "BAG", "", "bag", 296, 120, 40, 40),
			new Section("inventory", TYPE_TEXT, "gui.witchercraft.shell.section.stats", "", "stats", 12, 196, 200, 28),
			new Section("alchemy", TYPE_TEXT, "gui.witchercraft.shell.section.alchemy_todo", "", "todo", 12, 30, 300, 20),
			new Section("alchemy", TYPE_SLOT, "POTION", "", "potion1", 40, 60, 24, 24),
			new Section("alchemy", TYPE_SLOT, "POTION", "", "potion2", 72, 60, 24, 24),
			new Section("alchemy", TYPE_SLOT, "OIL", "", "oil1", 104, 60, 24, 24),
			new Section("bombs", TYPE_TEXT, "gui.witchercraft.shell.section.bombs_todo", "", "todo", 12, 30, 300, 20),
			new Section("bombs", TYPE_SLOT, "BOMB", "", "bomb1", 40, 60, 24, 24),
			new Section("bombs", TYPE_SLOT, "BOMB", "", "bomb2", 72, 60, 24, 24),
			new Section("map", TYPE_IMAGE, "MAP", "", "map", 20, 30, 320, 180),
			new Section("glossary", TYPE_TEXT, "gui.witchercraft.shell.section.glossary_todo", "", "todo", 12, 30, 300, 20),
	};

	// --- tiny lookups (kept trivial so the tool can regenerate the class) -----

	/** Sections belonging to a page, in declaration order. */
	public static java.util.List<Section> sectionsFor(String pageId) {
		java.util.List<Section> out = new java.util.ArrayList<>();
		for (Section s : SECTIONS)
			if (s.pageId.equals(pageId))
				out.add(s);
		return out;
	}

	/** Total pixel width the whole navbar group occupies. */
	public static int navTotalWidth(int count) {
		return count <= 0 ? 0 : count * NAV_TAB_W + (count - 1) * NAV_GAP;
	}

	/** Left edge of the first tab, so the group is centred on screen width. */
	public static int navStartX(int screenW, int count) {
		return (screenW - navTotalWidth(count)) / 2;
	}

	/** Left edge of tab i. */
	public static int navTabX(int screenW, int count, int i) {
		return navStartX(screenW, count) + i * (NAV_TAB_W + NAV_GAP);
	}

	/** Left edge of the centred content safe area. */
	public static int contentX(int screenW) {
		return (screenW - CONTENT_W) / 2;
	}

	/** Top edge of the content safe area: centred in the space below the navbar. */
	public static int contentY(int screenH) {
		int below = NAV_Y + NAV_H;
		int y = below + ((screenH - below) - CONTENT_H) / 2;
		return Math.max(below + 4, y);
	}
}
