package net.redboltmedia.witchercraft.client.gui.shell;

/**
 * Data-driven geometry for the WitcherCraft GUI shell CHROME: the virtual design
 * canvas, the fullscreen background, and the navbar. It does NOT describe page
 * content - each page owns its own layout (and its own placer tool), the way the
 * Skills page owns PerkEquipLayout / PerkTree. The shell just hands every page a
 * content REGION (the whole area below the navbar) to fill however it likes.
 *
 * The shell renders against a FIXED VIRTUAL DESIGN CANVAS (DESIGN_W x DESIGN_H,
 * 16:9) which WitcherGuiScreen scales uniformly to fit the real screen - so the
 * UI is independent of Minecraft's GUI scale and never distorted; non-16:9
 * screens get black letterbox bars. ALL coords are DESIGN-canvas pixels.
 *
 * Generated by tools/gui-layout-creator.html (navbar + chrome only) - paste this
 * over the file wholesale. Keep it a dumb data holder so the tool can overwrite
 * it freely.
 */
public final class WitcherGuiLayout {
	private WitcherGuiLayout() {
	}

	// --- virtual design canvas (16:9); the shell scales this to fit the screen -
	public static final int DESIGN_W = 640;
	public static final int DESIGN_H = 360;

	// --- fullscreen background --------------------------------------------------
	// Fallback used when a page has no entry in BACKGROUNDS below.
	public static final String BG = "witchercraft:textures/gui/shell/background.png";

	// --- navbar (centred group of fixed-width tabs, drawn over the background) -
	public static final int NAV_Y = 8;
	public static final int NAV_H = 30;
	public static final int NAV_TAB_W = 78;
	public static final int NAV_GAP = 4;
	public static final int NAV_ICON = 20;

	// --- content region (everything below the navbar; handed to the page) -----
	public static final int CONTENT_MARGIN = 3;

	// ==========================================================================
	//  A navbar tab. pageId must match a GuiPage.id() to be interactive. Tab
	//  positions are computed (centred) by the shell, so there is no rect here.
	// ==========================================================================
	public static final class Nav {
		public final String pageId;
		public final String labelKey; // lang key; may be "" to use the page's own label
		public final String icon; // texture path, or "" for none (label only)

		public Nav(String pageId, String labelKey, String icon) {
			this.pageId = pageId;
			this.labelKey = labelKey;
			this.icon = icon;
		}
	}

	// --- navbar ---------------------------------------------------------------
	public static final Nav[] NAV = {
			new Nav("glossary", "gui.witchercraft.shell.nav.glossary", "witchercraft:textures/gui/nav/glossary.png"),
			new Nav("alchemy", "gui.witchercraft.shell.nav.alchemy", "witchercraft:textures/gui/nav/alchemy.png"),
			new Nav("inventory", "gui.witchercraft.shell.nav.inventory", "witchercraft:textures/gui/nav/inventory.png"),
			new Nav("map", "gui.witchercraft.shell.nav.map", "witchercraft:textures/gui/nav/map.png"),
			new Nav("skills", "gui.witchercraft.shell.nav.skills", "witchercraft:textures/gui/nav/skills.png"),
			new Nav("bombs", "gui.witchercraft.shell.nav.bombs", "witchercraft:textures/gui/nav/bombs.png"),
			new Nav("meditation", "gui.witchercraft.shell.nav.meditation", "witchercraft:textures/gui/nav/meditation.png"),
	};

	// ==========================================================================
	//  Per-page background. A pageId with no entry here falls back to BG.
	// ==========================================================================
	public static final class Background {
		public final String pageId;
		public final String texture;

		public Background(String pageId, String texture) {
			this.pageId = pageId;
			this.texture = texture;
		}
	}

	public static final Background[] BACKGROUNDS = {
			new Background("inventory", "witchercraft:textures/gui/shell/backgrounds/inventory.png"),
			new Background("skills", "witchercraft:textures/gui/shell/backgrounds/skills.png"),
			new Background("alchemy", "witchercraft:textures/gui/shell/backgrounds/alchemy.png"),
			new Background("bombs", "witchercraft:textures/gui/shell/backgrounds/bombs.png"),
			new Background("map", "witchercraft:textures/gui/shell/backgrounds/map.png"),
			new Background("glossary", "witchercraft:textures/gui/shell/backgrounds/glossary.png"),
			new Background("meditation", "witchercraft:textures/gui/shell/backgrounds/meditation.png"),
	};

	// --- lookups (kept trivial so the tool can regenerate the class) ----------

	/** Background texture for a page: its own entry in BACKGROUNDS, or BG. */
	public static String backgroundFor(String pageId) {
		for (Background b : BACKGROUNDS)
			if (b.pageId.equals(pageId))
				return b.texture;
		return BG;
	}

	/** Total design-pixel width the whole navbar group occupies. */
	public static int navTotalWidth(int count) {
		return count <= 0 ? 0 : count * NAV_TAB_W + (count - 1) * NAV_GAP;
	}

	/** Left edge of the first tab, so the group is centred on the design canvas. */
	public static int navStartX(int count) {
		return (DESIGN_W - navTotalWidth(count)) / 2;
	}

	/** Left edge of tab i (design coords). */
	public static int navTabX(int count, int i) {
		return navStartX(count) + i * (NAV_TAB_W + NAV_GAP);
	}

	// --- content region: the whole area below the navbar (design coords) ------
	public static int contentX() {
		return CONTENT_MARGIN;
	}

	public static int contentY() {
		return NAV_Y + NAV_H + CONTENT_MARGIN;
	}

	public static int contentW() {
		return DESIGN_W - 2 * CONTENT_MARGIN;
	}

	public static int contentH() {
		return DESIGN_H - contentY() - CONTENT_MARGIN;
	}
}
