modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="witchercraft"
version="1.0.0"
displayName="WitcherCraft"
displayURL="https://redboltmedia.net"
credits="hm"
authors="Ciochu, RedBoltMedia"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.witchercraft]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.95,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.witchercraft]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration