package net.redboltmedia.witchercraft.client.gui;

/**
 * Data-driven geometry + colours for the meditation clock dial.
 *
 * All coordinates are PANEL-LOCAL (relative to a fixed PANEL_W x PANEL_H design
 * box). {@link net.redboltmedia.witchercraft.client.gui.shell.MeditationPage}
 * fit-scales this panel uniformly (centred) into the shell content region, the
 * same way the perk page maps {@link PerkEquipLayout}. Hours run clockwise with
 * 00:00 at the top (CX, CY - RADIUS): hour h sits at angle h/24 * 2PI.
 *
 * Generated by tools/meditation-dial-creator.html - paste this over the file
 * wholesale. Keep it a dumb data holder (no logic) so the tool can overwrite it.
 */
public final class MeditationLayout {
	private MeditationLayout() {
	}

	// Panel size (drives centering + fit-scale in the page).
	public static final int PANEL_W = 210;
	public static final int PANEL_H = 286;

	// Dial centre + radius (panel coords).
	public static final int CX = 105;
	public static final int CY = 110;
	public static final int RADIUS = 90;

	// Tick marks: every MAJOR_EVERY-th hour is a longer/thicker "major" tick and
	// gets a number label. len = inward length from the ring; half = half-width.
	public static final int MAJOR_EVERY = 6;
	public static final int TICK_MINOR_LEN = 5;
	public static final int TICK_MAJOR_LEN = 10;
	public static final int TICK_MINOR_HALF = 1;
	public static final int TICK_MAJOR_HALF = 2;

	// Distance from centre at which the major-hour number labels are centred.
	public static final int LABEL_RADIUS = 102;

	// Sun/moon target marker half-size (a small square on the ring at the target).
	public static final int GLYPH_HALF = 3;

	// Hands (from the hub outward). Current-time hand is dim/thin, target bright.
	public static final int HAND_CURRENT_LEN = 64;
	public static final int HAND_CURRENT_HALF = 1;
	public static final int HAND_TARGET_LEN = 80;
	public static final int HAND_TARGET_HALF = 2;
	public static final int HUB_HALF = 2;

	// Readout text baselines (centred on CX): current time then target time.
	public static final int NOW_Y = 222;
	public static final int TARGET_Y = 234;

	// "Meditate" button rect (panel coords).
	public static final int BTN_X = 45;
	public static final int BTN_Y = 250;
	public static final int BTN_W = 120;
	public static final int BTN_H = 20;

	// --- colours (0xAARRGGBB) --------------------------------------------------
	public static final int COL_TICK_MINOR = 0xFF55555F;
	public static final int COL_TICK_MAJOR = 0xFFCFC7B0;
	public static final int COL_HAND_CURRENT = 0xFF8899AA;
	public static final int COL_HAND_TARGET = 0xFFFFDD55;
	public static final int COL_HUB = 0xFFCFC7B0;
	public static final int COL_SUN = 0xFFFFCC33;
	public static final int COL_MOON = 0xFFAAB6CC;
	public static final int COL_TEXT_TITLE = 0xFFCFC7B0;
	public static final int COL_TEXT_SUB = 0xFF9A9AA2;
	public static final int COL_BTN_BG = 0x66101015;
	public static final int COL_BTN_BG_HOVER = 0xB0000000;
	public static final int COL_BTN_BORDER = 0xFF33333D;
	public static final int COL_BTN_TEXT = 0xFFFFDD55;

	/** Uniform scale to fit the panel into a w x h content region. */
	public static float fitScale(int w, int h) {
		return Math.min((float) w / PANEL_W, (float) h / PANEL_H);
	}
}
