package net.redboltmedia.witchercraft.client.gui;

import java.util.ArrayList;
import java.util.List;

/**
 * Perk-tree topology: node positions (GUI-local, left half of the equip screen)
 * and per-node prerequisites. A node's branch is its colour = perkId / 100.
 *
 * Generated by tools/tree-node-placer.html - paste this over the file wholesale.
 */
public final class PerkTree {
	private PerkTree() {
	}

	public static final int NODE_SIZE = 24;

	public static final class Node {
		public final int perkId;
		public final int x, y;
		public final int[] prereqs;

		Node(int perkId, int x, int y, int... prereqs) {
			this.perkId = perkId;
			this.x = x;
			this.y = y;
			this.prereqs = prereqs;
		}

		public int cx() {
			return x + NODE_SIZE / 2;
		}

		public int cy() {
			return y + NODE_SIZE / 2;
		}
	}

	public static final Node[] NODES = {
			new Node(101, 0, 24),
			new Node(102, 66, 24),
			new Node(103, 160, 24),
			new Node(104, 8, 56),
			new Node(105, 66, 56),
			new Node(106, 124, 56),
			new Node(107, 8, 88),
			new Node(108, 66, 88),
			new Node(109, 124, 88),
			new Node(110, 8, 120),
			new Node(111, 66, 120),
			new Node(112, 124, 120),
			new Node(113, 8, 152),
			new Node(114, 66, 152),
			new Node(115, 124, 152),
			new Node(201, 8, 24),
			new Node(202, 66, 24),
			new Node(203, 124, 24),
			new Node(204, 8, 56),
			new Node(205, 66, 56),
			new Node(206, 124, 56),
			new Node(207, 8, 88),
			new Node(208, 66, 88),
			new Node(209, 124, 88),
			new Node(301, 8, 24),
			new Node(302, 66, 24),
			new Node(303, 124, 24),
			new Node(304, 8, 56),
			new Node(305, 66, 56),
			new Node(306, 124, 56),
			new Node(307, 8, 88),
			new Node(308, 66, 88),
			new Node(309, 124, 88),
			new Node(310, 8, 120),
			new Node(311, 66, 120),
			new Node(312, 124, 120),
			new Node(313, 8, 152),
			new Node(314, 66, 152),
			new Node(315, 124, 152),
			new Node(401, 8, 24),
			new Node(402, 66, 24),
			new Node(403, 124, 24),
			new Node(404, 8, 56),
			new Node(405, 66, 56),
			new Node(406, 124, 56),
	};

	public static Node byId(int perkId) {
		for (Node n : NODES)
			if (n.perkId == perkId)
				return n;
		return null;
	}

	/** nodes belonging to a branch colour (1 red / 2 green / 3 blue / 4 neutral). */
	public static List<Node> forColor(int color) {
		List<Node> out = new ArrayList<>();
		for (Node n : NODES)
			if (n.perkId / 100 == color)
				out.add(n);
		return out;
	}
}
