
package net.redboltmedia.witchercraft.client.gui;

/**
 * Data-driven geometry for the perk equip panel.
 *
 * All coordinates are GUI-LOCAL (relative to the screen's top-left), in the
 * same space MCreator's extractLabels() uses, so they can be passed straight to
 * guiGraphics.text / drawing calls. When blitting in extractBackground(), add
 * leftPos / topPos yourself.
 *
 * This whole class is intended to be REGENERATED by the standalone HTML
 * node-placer tool (see plan Section 6): the placer loads a background image,
 * lets the designer drag the 12 perk slots + 4 mutagen sockets + medallion, and
 * emits exactly these arrays. Keep it a dumb data holder - no logic here - so
 * the tool can overwrite it wholesale.
 */
public final class PerkEquipLayout {
	private PerkEquipLayout() {
	}

	// Panel size (drives centering via leftPos/topPos in the Screen).
	public static final int PANEL_W = 256;
	public static final int PANEL_H = 200;

	public static final int SLOT_SIZE = 24;
	public static final int SOCKET_SIZE = 24;
	public static final int MEDALLION_SIZE = 40;

	// 12 perk slots, grouped 0-2 / 3-5 / 6-8 / 9-11 into the 4 mutagen groups.
	// Two columns left of the central medallion, two columns right.
	public static final int[] SLOT_X = {16, 16, 16, 52, 52, 52, 180, 180, 180, 216, 216, 216};
	public static final int[] SLOT_Y = {40, 72, 104, 40, 72, 104, 40, 72, 104, 40, 72, 104};

	// 4 mutagen sockets, one under each column.
	public static final int[] SOCKET_X = {16, 52, 180, 216};
	public static final int[] SOCKET_Y = {140, 140, 140, 140};

	// Central mutagen medallion (decorative anchor).
	public static final int MEDALLION_X = 108;
	public static final int MEDALLION_Y = 64;

	/** Which mutagen group (0-3) a perk slot index (0-11) belongs to. */
	public static int groupOfSlot(int slotIndex) {
		return slotIndex / 3;
	}
}
