package net.redboltmedia.witchercraft;

/**
 * Geometry of the Alchemy tab's SLOT BLOCK: the alchemy circle (base in the
 * centre, five ingredients around it), the output slot, and the player
 * inventory. Shared by {@link AlchemyMenu} (slot positions) and
 * {@link AlchemyScreen} (drawing and placement).
 *
 * Unlike the other shell layouts, these are NORMAL GUI pixels, not the 640x360
 * design canvas: real item slots draw at vanilla scale so vanilla handles every
 * click, drag and tooltip. Slot coords are the 16x16 item position inside the
 * block, like vanilla {@code Slot} x/y; the 18x18 frame is drawn 1px outside.
 *
 * The whole block (with the recipe book panel to its left) is centred in the
 * shell's content region, then shifted by BLOCK_OFFSET_X/Y.
 *
 * Generated by tools/alchemy-layout-placer.html - paste this over the file
 * wholesale. Keep it a dumb data holder (no logic) so the tool can overwrite it.
 */
public final class AlchemyLayout {
	private AlchemyLayout() {
	}

	// --- slot block size and placement (GUI pixels) --------------------------
	public static final int BLOCK_W = 176;
	public static final int BLOCK_H = 180;
	public static final int BLOCK_OFFSET_X = 0;
	public static final int BLOCK_OFFSET_Y = 0;

	// --- recipe book panel, left of the block (reserved space until slice 3) --
	public static final int BOOK_W = 147;
	public static final int BOOK_H = 166;
	public static final int BOOK_GAP = 4;

	// --- alchemy circle --------------------------------------------------------
	public static final int BASE_X = 62;
	public static final int BASE_Y = 36;
	// ingredient slots clockwise from the top
	public static final int[] INGREDIENT_X = {62, 92, 81, 43, 32};
	public static final int[] INGREDIENT_Y = {4, 26, 62, 62, 26};

	// --- output ------------------------------------------------------------------
	public static final int OUTPUT_X = 144;
	public static final int OUTPUT_Y = 36;

	// --- Brew button ---------------------------------------------------------------
	public static final int BREW_X = 135;
	public static final int BREW_Y = 58;
	public static final int BREW_W = 34;
	public static final int BREW_H = 14;
	public static final int BREW_TEXT_COLOR = 0xFFE8D9A8;
	public static final int BREW_TEXT_HOVER_COLOR = 0xFFFFDD55;

	// --- brew feedback ("Nothing happens."), below the Brew button ----------------
	// Centred on MESSAGE_CENTER_X, wrapped to MESSAGE_W, shown for MESSAGE_MS and
	// faded out over the last MESSAGE_FADE_MS. MESSAGE_COLOR is 0xRRGGBB (no alpha).
	public static final int MESSAGE_CENTER_X = 152;
	public static final int MESSAGE_Y = 75;
	public static final int MESSAGE_W = 64;
	public static final int MESSAGE_COLOR = 0xE8D9A8;
	public static final int MESSAGE_MS = 2000;
	public static final int MESSAGE_FADE_MS = 500;

	// --- player inventory (3 rows) and hotbar -----------------------------------
	public static final int INVENTORY_X = 8;
	public static final int INVENTORY_Y = 98;
	public static final int HOTBAR_Y = 156;

	// --- art ---------------------------------------------------------------------
	// Every piece is drawn with the slot block (never baked into the fullscreen tab
	// background), so it stays aligned at every GUI scale and window size. Slot
	// sprites are 18x18 and drawn at each slot's frame (1px outside the item), so
	// moving a slot moves its art. An empty path draws nothing.
	public static final String SLOT_BASE_TEX = "witchercraft:textures/screens/alchemy_slot_base.png";
	public static final String SLOT_INGREDIENT_TEX = "witchercraft:textures/screens/alchemy_slot_ingredient.png";
	public static final String SLOT_OUTPUT_TEX = "witchercraft:textures/screens/alchemy_slot_output.png";
	public static final String SLOT_INVENTORY_TEX = "witchercraft:textures/screens/alchemy_slot_inventory.png";
	public static final int SLOT_TEX_SIZE = 18;

	// behind the whole block, BLOCK_W x BLOCK_H
	public static final String PANEL_TEX = "witchercraft:textures/screens/alchemy_panel.png";
	// behind the recipe book panel, BOOK_W x BOOK_H
	public static final String BOOK_TEX = "witchercraft:textures/screens/alchemy_book_panel.png";

	// Brew button, BREW_W x BREW_H; the label is drawn by code on top
	public static final String BREW_TEX = "witchercraft:textures/screens/alchemy_brew_button.png";
	public static final String BREW_HOVER_TEX = "witchercraft:textures/screens/alchemy_brew_button_hover.png";

	// ornament behind the circle slots, drawn at this rect inside the block
	public static final String CIRCLE_TEX = "witchercraft:textures/screens/alchemy_circle_frame.png";
	public static final int CIRCLE_X = 26;
	public static final int CIRCLE_Y = 0;
	public static final int CIRCLE_W = 88;
	public static final int CIRCLE_H = 88;

	// outline when the block or book panel does not fit the content region
	public static final int MISFIT_COLOR = 0xFFD04040;
}
