package net.redboltmedia.witchercraft;

/** Generated by tools/map-layout-creator.html. */
public final class MapLayout {
	private MapLayout() {}

	public static final int VIEW_X = -3;
	public static final int VIEW_Y = -4;
	public static final int VIEW_W = 639;
	public static final int VIEW_H = 286;
	public static final int BAR_X = -4;
	public static final int BAR_Y = 281;
	public static final int BAR_W = 640;
	public static final int BAR_H = 35;
	public static final int BUTTON_Y = 7;
	public static final int BUTTON_H = 21;
	public static final int BUTTON_GAP = 5;
	public static final int WAYPOINTS_X = 8;
	public static final int WAYPOINTS_W = 70;
	public static final int FILTERS_X = 83;
	public static final int FILTERS_W = 55;
	public static final int CENTER_X = 436;
	public static final int CENTER_W = 64;
	public static final int ZOOM_OUT_X = 505;
	public static final int ZOOM_W = 28;
	public static final int ZOOM_IN_X = 538;
	public static final int COORD_X = 146;
	public static final int COORD_Y = 13;
	public static final int HINT_X = 574;
	public static final int HINT_Y = 13;
	public static final int HELP_X = 146;
	public static final int HELP_Y = 13;
	public static final int HELP_W = 282;
	public static final int CREATE_W = 250;
	public static final int CREATE_H = 142;
	public static final int CREATE_PADDING = 14;
	public static final int CREATE_NAME_Y = 34;
	public static final int CREATE_NAME_H = 18;
	public static final int CREATE_ICON_Y = 68;
	public static final int CREATE_ICON_SIZE = 24;
	public static final int CREATE_ICON_GAP = 5;
	public static final int CREATE_ACTION_Y = 113;
	public static final int CREATE_ACTION_W = 68;
	public static final int MANAGER_W = 390;
	public static final int MANAGER_H = 190;
	public static final int MANAGER_PADDING = 12;
	public static final int MANAGER_SEARCH_Y = 30;
	public static final int MANAGER_SEARCH_H = 18;
	public static final int MANAGER_LIST_Y = 56;
	public static final int MANAGER_ROW_H = 29;
	public static final int MANAGER_VISIBLE_ROWS = 4;
	public static final int MANAGER_ACTION_X = 230;
	public static final int SELECTION_W = 280;
	public static final int SELECTION_H = 40;
	public static final int SELECTION_BOTTOM = 6;
	public static final int CONTEXT_W = 136;
	public static final int CONTEXT_H = 58;
	public static final int CONTEXT_PADDING = 8;
	public static final int CONTEXT_MARKER_GAP = 5;

	public static final int VIEW_BG = 0xFF11151A;
	public static final int VIEW_BORDER = 0xFF665E4A;
	public static final int GRID_MINOR = 0xFF252C31;
	public static final int GRID_MAJOR = 0xFF485057;
	public static final int GRID_AXIS = 0xFF9B704D;
	public static final int BAR_BG = 0xE6121217;
	public static final int BUTTON_BG = 0xFF26262E;
	public static final int BUTTON_HOVER = 0xFF393944;
	public static final int BUTTON_DISABLED = 0xFF19191E;
	public static final int TEXT = 0xFFE4DDCB;
	public static final int TEXT_DIM = 0xFF777781;
	public static final int OVERLAY_DIM = 0xB8000000;
	public static final int OVERLAY_BG = 0xFF17171C;
	public static final int OVERLAY_BORDER = 0xFF9B704D;
	public static final int FIELD_BG = 0xFF0D0D11;
	public static final int SELECTED = 0xFFD6AD52;
	public static final int ERROR = 0xFFE06A5F;
	/** Edit this ARGB value to test the saved-waypoint icon, name, and selection-card color. */
	public static final int WAYPOINT_COLOR = 0xFFD6AD52;
}
