package net.redboltmedia.witchercraft;

/** Generated by tools/map-layout-creator.html. */
public final class MapLayout {
	private MapLayout() {}

	public static final int VIEW_X = -3;
	public static final int VIEW_Y = -4;
	public static final int VIEW_W = 639;
	public static final int VIEW_H = 286;
	public static final int BAR_X = -4;
	public static final int BAR_Y = 281;
	public static final int BAR_W = 640;
	public static final int BAR_H = 35;
	public static final int BUTTON_Y = 7;
	public static final int BUTTON_H = 21;
	public static final int BUTTON_GAP = 5;
	public static final int WAYPOINTS_X = 8;
	public static final int WAYPOINTS_W = 70;
	public static final int FILTERS_X = 83;
	public static final int FILTERS_W = 55;
	public static final int CENTER_X = 436;
	public static final int CENTER_W = 64;
	public static final int ZOOM_OUT_X = 505;
	public static final int ZOOM_W = 28;
	public static final int ZOOM_IN_X = 538;
	public static final int COORD_X = 146;
	public static final int COORD_Y = 13;
	public static final int HINT_X = 574;
	public static final int HINT_Y = 13;

	public static final int VIEW_BG = 0xFF11151A;
	public static final int VIEW_BORDER = 0xFF665E4A;
	public static final int GRID_MINOR = 0xFF252C31;
	public static final int GRID_MAJOR = 0xFF485057;
	public static final int GRID_AXIS = 0xFF9B704D;
	public static final int BAR_BG = 0xE6121217;
	public static final int BUTTON_BG = 0xFF26262E;
	public static final int BUTTON_HOVER = 0xFF393944;
	public static final int BUTTON_DISABLED = 0xFF19191E;
	public static final int TEXT = 0xFFE4DDCB;
	public static final int TEXT_DIM = 0xFF777781;
	public static final int PLAYER = 0xFFFFDD55;
}
