package net.redboltmedia.witchercraft;

/**
 * Data-driven geometry + colours for the meditation clock dial.
 *
 * All coordinates are PANEL-LOCAL (relative to a fixed PANEL_W x PANEL_H design
 * box). {@link net.redboltmedia.witchercraft.MeditationPage}
 * fit-scales this panel uniformly (centred) into the shell content region, the
 * same way the perk page maps {@link PerkEquipLayout}. The dial reads day-up:
 * hour h sits at angle h/24 * 2PI + PI, so NOON is at the top and 00:00 at the
 * bottom (see MeditationPage.hourAngle).
 *
 * Generated by tools/meditation-dial-creator.html - paste this over the file
 * wholesale. Keep it a dumb data holder (no logic) so the tool can overwrite it.
 */
public final class MeditationLayout {
	private MeditationLayout() {
	}

	// Panel size (drives centering + fit-scale in the page).
	public static final int PANEL_W = 224;
	public static final int PANEL_H = 300;

	// Dial centre + radius (panel coords).
	public static final int CX = 112;
	public static final int CY = 112;
	public static final int RADIUS = 82;

	// Tick marks: every MAJOR_EVERY-th hour is a longer/thicker "major" tick. len =
	// inward length from the ring; half = half-width. Numbers are optional (the orbs
	// double as the time legend) - SHOW_NUMBERS != 0 labels the major hours.
	public static final int MAJOR_EVERY = 6;
	public static final int TICK_MINOR_LEN = 5;
	public static final int TICK_MAJOR_LEN = 10;
	public static final int TICK_MINOR_HALF = 1;
	public static final int TICK_MAJOR_HALF = 2;
	public static final int SHOW_NUMBERS = 0;
	// Distance from centre at which the major-hour number labels are centred.
	public static final int LABEL_RADIUS = 98;

	// Time-of-day orbs (32x32 sprites) placed at four fixed hours around the ring.
	// ORB_RADIUS = distance of each orb centre from the dial centre; ORB_SIZE = the
	// drawn size in panel px (the source is ORB_SRC square).
	public static final int ORB_SRC = 32;
	public static final int ORB_RADIUS = 88;
	public static final int ORB_SIZE = 30;
	public static final int ORB_DAWN_HOUR = 6;
	public static final int ORB_NOON_HOUR = 12;
	public static final int ORB_DUSK_HOUR = 18;
	public static final int ORB_NIGHT_HOUR = 0;
	public static final String ORB_DAWN_TEX = "witchercraft:textures/screens/meditationguitimedawn.png";
	public static final String ORB_NOON_TEX = "witchercraft:textures/screens/meditationguitimenoon.png";
	public static final String ORB_DUSK_TEX = "witchercraft:textures/screens/meditationguitimedusk.png";
	public static final String ORB_NIGHT_TEX = "witchercraft:textures/screens/meditationguitimenight.png";

	// Hands, drawn as arrows from the hub outward. LEN = tip distance from centre,
	// HALF = shaft half-width; the shared arrowhead is HAND_HEAD_LEN long and
	// HAND_HEAD_HALF wide at its base. Current-time hand is dim/thin, target bright.
	public static final int HAND_CURRENT_LEN = 58;
	public static final int HAND_CURRENT_HALF = 1;
	public static final int HAND_TARGET_LEN = 72;
	public static final int HAND_TARGET_HALF = 2;
	public static final int HAND_HEAD_LEN = 12;
	public static final int HAND_HEAD_HALF = 4;
	public static final int HUB_HALF = 3;

	// Progress arc: a thin sweep from the current hour forward to the target hour
	// (the time that will pass), at ARC_RADIUS, ARC_HALF px thick.
	public static final int ARC_RADIUS = 68;
	public static final int ARC_HALF = 0;

	// Readout text baselines (centred on CX): current time then target time.
	public static final int NOW_Y = 232;
	public static final int TARGET_Y = 244;

	// "Meditate" button rect (panel coords).
	public static final int BTN_X = 52;
	public static final int BTN_Y = 262;
	public static final int BTN_W = 120;
	public static final int BTN_H = 20;

	// --- colours (0xAARRGGBB) --------------------------------------------------
	public static final int COL_TICK_MINOR = 0xFF55555F;
	public static final int COL_TICK_MAJOR = 0xFFCFC7B0;
	public static final int COL_HAND_CURRENT = 0xFF8899AA;
	public static final int COL_HAND_TARGET = 0xFFFFDD55;
	public static final int COL_HUB = 0xFFCFC7B0;
	public static final int COL_ARC = 0xAAFFCF66;
	public static final int COL_TEXT_TITLE = 0xFFCFC7B0;
	public static final int COL_TEXT_SUB = 0xFF9A9AA2;
	public static final int COL_BTN_BG = 0x66101015;
	public static final int COL_BTN_BG_HOVER = 0xB0000000;
	public static final int COL_BTN_BORDER = 0xFF33333D;
	public static final int COL_BTN_TEXT = 0xFFFFDD55;

	/** Uniform scale to fit the panel into a w x h content region. */
	public static float fitScale(int w, int h) {
		return Math.min((float) w / PANEL_W, (float) h / PANEL_H);
	}
}
