package net.redboltmedia.witchercraft;

/**
 * Data-driven geometry for the WitcherCraft pause menu.
 *
 * The pause menu works just like the shell navbar - a centred group of
 * fixed-width tabs - only BIGGER, drawn over its own background. Each tab opens
 * the shell on the matching page ({@code new WitcherGuiScreen(pageId)}), so its
 * tab set mirrors the navbar. It renders against the shell's virtual design
 * canvas and also draws the same level/XP readout
 * ({@link WitcherGuiScreen#drawLevelReadout}), which is edited in the navbar
 * tool; this class owns only the pause chrome: canvas, background and the tabs.
 *
 * {@link net.redboltmedia.witchercraft.client.gui.PauseMenuGuiScreen} reads this
 * and keeps only render + input logic (the tab palette is hardcoded there, the
 * same way the shell navbar's is).
 *
 * Generated by tools/pause-menu-creator.html - paste this over the file
 * wholesale. Keep it a dumb data holder so the tool can overwrite it freely.
 */
public final class PauseMenuLayout {
	private PauseMenuLayout() {
	}

	// --- virtual design canvas (16:9); the screen scales this to fit -----------
	public static final int DESIGN_W = 640;
	public static final int DESIGN_H = 360;

	// --- background (fills the 16:9 design canvas; black letterbox elsewhere) --
	public static final String BG = "witchercraft:textures/gui/shell/background.png";

	// --- navbar (centred group of fixed-width tabs; bigger than the shell's) ---
	public static final int NAV_Y = 150;
	public static final int NAV_H = 44;
	public static final int NAV_TAB_W = 92;
	public static final int NAV_GAP = 6;
	public static final int NAV_ICON = 28;

	// ==========================================================================
	//  A pause tab. pageId is the shell page it opens (new WitcherGuiScreen(id)).
	//  Positions are computed (centred) by the screen, so there is no rect here.
	// ==========================================================================
	public static final class Nav {
		public final String pageId;
		public final String labelKey; // lang key; may be "" to use the page's own label
		public final String icon; // texture path, or "" for none (label only)

		public Nav(String pageId, String labelKey, String icon) {
			this.pageId = pageId;
			this.labelKey = labelKey;
			this.icon = icon;
		}
	}

	// --- tabs (same set as the navbar) ----------------------------------------
	public static final Nav[] NAV = {
			new Nav("glossary", "gui.witchercraft.shell.nav.glossary", "witchercraft:textures/gui/nav/glossary.png"),
			new Nav("alchemy", "gui.witchercraft.shell.nav.alchemy", "witchercraft:textures/gui/nav/alchemy.png"),
			new Nav("inventory", "gui.witchercraft.shell.nav.inventory", "witchercraft:textures/gui/nav/inventory.png"),
			new Nav("map", "gui.witchercraft.shell.nav.map", "witchercraft:textures/gui/nav/map.png"),
			new Nav("skills", "gui.witchercraft.shell.nav.skills", "witchercraft:textures/gui/nav/skills.png"),
			new Nav("meditation", "gui.witchercraft.shell.nav.meditation", "witchercraft:textures/gui/nav/meditation.png"),
	};

	// --- lookups (kept trivial so the tool can regenerate the class) ----------

	/** Total design-pixel width the whole tab group occupies. */
	public static int navTotalWidth(int count) {
		return count <= 0 ? 0 : count * NAV_TAB_W + (count - 1) * NAV_GAP;
	}

	/** Left edge of the first tab, so the group is centred on the design canvas. */
	public static int navStartX(int count) {
		return (DESIGN_W - navTotalWidth(count)) / 2;
	}

	/** Left edge of tab i (design coords). */
	public static int navTabX(int count, int i) {
		return navStartX(count) + i * (NAV_TAB_W + NAV_GAP);
	}
}
