package net.redboltmedia.witchercraft;

/**
 * Data-driven geometry and colours for the Skills panel: the right side (perk
 * equip grid, mutagen sockets, bonus labels, medallion) and every colour. The
 * sub-tabs, tree and Mutagens inventory block are in PerkTree.
 *
 * All coordinates are PANEL-LOCAL Minecraft GUI pixels: the 360x200 panel is
 * drawn 1:1 at normal GUI scale, centred below the navbar (PerkPage.origin),
 * and SkillsMenu places its real slots from these same values. Every cell is a
 * vanilla slot: an 18x18 frame (x, y = its top-left) around a 16x16 icon.
 *
 * Generated by tools/equip-grid-placer.html - paste this over the file wholesale.
 * Keep it a dumb data holder (no logic) so the tool can overwrite it.
 */
public final class PerkEquipLayout {
	private PerkEquipLayout() {
	}

	// Panel size (centred in the content region below the navbar).
	public static final int PANEL_W = 360;
	public static final int PANEL_H = 200;

	// Fixed: every cell is a vanilla slot (18x18 frame, 16x16 icon).
	public static final int SLOT_SIZE = 18;
	public static final int SOCKET_SIZE = 18;

	// --- Equip grid (right half): 12 perk slots, grouped 0-2 / 3-5 / 6-8 /
	// 9-11 into the 4 mutagen groups. Two columns left of the central
	// medallion, two columns right (W3 geometry).
	public static final int[] SLOT_X = {248, 248, 248, 246, 246, 246, 278, 278, 278, 278, 278, 278};
	public static final int[] SLOT_Y = {2, 30, 57, 111, 138, 166, 2, 30, 57, 111, 138, 166};

	// 4 mutagen sockets (real item slots), socket i next to perk group i.
	public static final int[] SOCKET_X = {210, 208, 316, 316};
	public static final int[] SOCKET_Y = {30, 138, 30, 138};

	// Central medallion: a resizable rectangular region (W3 decorative anchor by
	// default; can be repurposed as a button later). Not drawn when disabled.
	public static final boolean MEDALLION_ENABLED = true;
	public static final int MEDALLION_X = 252;
	public static final int MEDALLION_Y = 83;
	public static final int MEDALLION_W = 40;
	public static final int MEDALLION_H = 20;

	// What each mutagen socket gives ("+15 Increased Damage", one line per bonus,
	// 10px apart at scale 1, BONUS_TEXT on a BONUS_BG background, both picked by
	// the socketed mutagen's type: 0 red, 1 green, 2 blue): a box per
	// socket, the text left- or right-aligned inside it (not clipped).
	public static final int[] BONUS_X = {158, 116, 248, 248};
	public static final int[] BONUS_Y = {50, 158, 50, 158};
	public static final int[] BONUS_W = {70, 110, 110, 110};
	public static final boolean[] BONUS_ALIGN_RIGHT = {true, true, true, true};
	public static final float BONUS_TEXT_SCALE = 1f;

	// --- Colours (ARGB, 0xAARRGGBB). Edited in the tool's Colours panel.
	public static final int[] BRANCH_COLORS = {0xFFFF5555, 0xFF55FF55, 0xFF5599FF, 0xFFCCCCCC};
	public static final int TAB_BORDER = 0xFF4A4A52;
	public static final int TAB_INNER = 0xFF1B1B20;
	public static final int[] TAB_ACTIVE_BORDER = {0xFFFF5555, 0xFF55FF55, 0xFF5599FF, 0xFFCCCCCC, 0xFFB03030};
	public static final int TAB_FADE = 0x66FFFFFF;
	public static final int CELL_BORDER = 0xFF4A4A52;
	public static final int CELL_INNER = 0xFF1B1B20;
	public static final int TARGET_BORDER = 0xFFFFDD55;
	public static final int NODE_AVAILABLE_INNER = 0xFF141417;
	public static final int NODE_LOCKED_BORDER = 0xFF2A2A30;
	public static final int NODE_LOCKED_INNER = 0xFF121215;
	public static final int LINK_LOCKED = 0xFF3A3A42;
	public static final int[] BONUS_TEXT = {0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF};
	public static final int[] BONUS_BG = {0xAAFF5555, 0xFF55FF55, 0xFF5599FF};
	public static final int STATUS_POINTS = 0xFFDDDD88;
	public static final int STATUS_TEXT = 0xFF9A9AA2;
	public static final int MEDALLION_BORDER = 0xFF8A6D3B;
	public static final int MEDALLION_INNER = 0xFF3A2E1C;
	public static final int MEDALLION_TEXT = 0xFFEEDDBB;

	/** Which mutagen group (0-3) a perk slot index (0-11) belongs to. */
	public static int groupOfSlot(int slotIndex) {
		return slotIndex / 3;
	}
}
